/* tslint:disable */
/* eslint-disable */
/**
 * Todo List API
 * A basic todo list API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Csrfmiddlewaretoken
 */
export interface Csrfmiddlewaretoken {
    /**
     * 
     * @type {string}
     * @memberof Csrfmiddlewaretoken
     */
    csrfmiddlewaretoken: string;
}

/**
 * Check if a given object implements the Csrfmiddlewaretoken interface.
 */
export function instanceOfCsrfmiddlewaretoken(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "csrfmiddlewaretoken" in value;

    return isInstance;
}

export function CsrfmiddlewaretokenFromJSON(json: any): Csrfmiddlewaretoken {
    return CsrfmiddlewaretokenFromJSONTyped(json, false);
}

export function CsrfmiddlewaretokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): Csrfmiddlewaretoken {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'csrfmiddlewaretoken': json['csrfmiddlewaretoken'],
    };
}

export function CsrfmiddlewaretokenToJSON(value?: Csrfmiddlewaretoken | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'csrfmiddlewaretoken': value.csrfmiddlewaretoken,
    };
}

