/* tslint:disable */
/* eslint-disable */
/**
 * Todo List API
 * A basic todo list API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DrfAuthtoken
 */
export interface DrfAuthtoken {
    /**
     * 
     * @type {string}
     * @memberof DrfAuthtoken
     */
    readonly token?: string;
}

/**
 * Check if a given object implements the DrfAuthtoken interface.
 */
export function instanceOfDrfAuthtoken(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DrfAuthtokenFromJSON(json: any): DrfAuthtoken {
    return DrfAuthtokenFromJSONTyped(json, false);
}

export function DrfAuthtokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): DrfAuthtoken {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'token': !exists(json, 'token') ? undefined : json['token'],
    };
}

export function DrfAuthtokenToJSON(value?: DrfAuthtoken | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}

