/* tslint:disable */
/* eslint-disable */
/**
 * Todo List API
 * A basic todo list API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GCMDeviceRequest
 */
export interface GCMDeviceRequest {
    /**
     * 
     * @type {string}
     * @memberof GCMDeviceRequest
     */
    registrationId: string;
}

/**
 * Check if a given object implements the GCMDeviceRequest interface.
 */
export function instanceOfGCMDeviceRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "registrationId" in value;

    return isInstance;
}

export function GCMDeviceRequestFromJSON(json: any): GCMDeviceRequest {
    return GCMDeviceRequestFromJSONTyped(json, false);
}

export function GCMDeviceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GCMDeviceRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'registrationId': json['registration_id'],
    };
}

export function GCMDeviceRequestToJSON(value?: GCMDeviceRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'registration_id': value.registrationId,
    };
}

