/* tslint:disable */
/* eslint-disable */
/**
 * Todo List API
 * A basic todo list API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Serializer for confirming a password reset attempt.
 * @export
 * @interface PasswordResetConfirmRequest
 */
export interface PasswordResetConfirmRequest {
    /**
     * 
     * @type {string}
     * @memberof PasswordResetConfirmRequest
     */
    newPassword1: string;
    /**
     * 
     * @type {string}
     * @memberof PasswordResetConfirmRequest
     */
    newPassword2: string;
    /**
     * 
     * @type {string}
     * @memberof PasswordResetConfirmRequest
     */
    uid: string;
    /**
     * 
     * @type {string}
     * @memberof PasswordResetConfirmRequest
     */
    token: string;
}

/**
 * Check if a given object implements the PasswordResetConfirmRequest interface.
 */
export function instanceOfPasswordResetConfirmRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "newPassword1" in value;
    isInstance = isInstance && "newPassword2" in value;
    isInstance = isInstance && "uid" in value;
    isInstance = isInstance && "token" in value;

    return isInstance;
}

export function PasswordResetConfirmRequestFromJSON(json: any): PasswordResetConfirmRequest {
    return PasswordResetConfirmRequestFromJSONTyped(json, false);
}

export function PasswordResetConfirmRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PasswordResetConfirmRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'newPassword1': json['new_password1'],
        'newPassword2': json['new_password2'],
        'uid': json['uid'],
        'token': json['token'],
    };
}

export function PasswordResetConfirmRequestToJSON(value?: PasswordResetConfirmRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'new_password1': value.newPassword1,
        'new_password2': value.newPassword2,
        'uid': value.uid,
        'token': value.token,
    };
}

