/* tslint:disable */
/* eslint-disable */
/**
 * Todo List API
 * A basic todo list API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedTodo
 */
export interface PatchedTodo {
    /**
     * 
     * @type {number}
     * @memberof PatchedTodo
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedTodo
     */
    content?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedTodo
     */
    isCompleted?: boolean;
}

/**
 * Check if a given object implements the PatchedTodo interface.
 */
export function instanceOfPatchedTodo(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchedTodoFromJSON(json: any): PatchedTodo {
    return PatchedTodoFromJSONTyped(json, false);
}

export function PatchedTodoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedTodo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'content': !exists(json, 'content') ? undefined : json['content'],
        'isCompleted': !exists(json, 'is_completed') ? undefined : json['is_completed'],
    };
}

export function PatchedTodoToJSON(value?: PatchedTodo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'content': value.content,
        'is_completed': value.isCompleted,
    };
}

