/* tslint:disable */
/* eslint-disable */
/**
 * Todo List API
 * A basic todo list API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * User model w/o password
 * @export
 * @interface PatchedUserDetailsRequest
 */
export interface PatchedUserDetailsRequest {
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     * @type {string}
     * @memberof PatchedUserDetailsRequest
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedUserDetailsRequest
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedUserDetailsRequest
     */
    lastName?: string;
}

/**
 * Check if a given object implements the PatchedUserDetailsRequest interface.
 */
export function instanceOfPatchedUserDetailsRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchedUserDetailsRequestFromJSON(json: any): PatchedUserDetailsRequest {
    return PatchedUserDetailsRequestFromJSONTyped(json, false);
}

export function PatchedUserDetailsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedUserDetailsRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'username': !exists(json, 'username') ? undefined : json['username'],
        'firstName': !exists(json, 'first_name') ? undefined : json['first_name'],
        'lastName': !exists(json, 'last_name') ? undefined : json['last_name'],
    };
}

export function PatchedUserDetailsRequestToJSON(value?: PatchedUserDetailsRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
        'first_name': value.firstName,
        'last_name': value.lastName,
    };
}

