/* tslint:disable */
/* eslint-disable */
/**
 * Todo List API
 * A basic todo list API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedTodoRequest
 */
export interface PatchedTodoRequest {
    /**
     * 
     * @type {string}
     * @memberof PatchedTodoRequest
     */
    content?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedTodoRequest
     */
    isCompleted?: boolean;
}

/**
 * Check if a given object implements the PatchedTodoRequest interface.
 */
export function instanceOfPatchedTodoRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchedTodoRequestFromJSON(json: any): PatchedTodoRequest {
    return PatchedTodoRequestFromJSONTyped(json, false);
}

export function PatchedTodoRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedTodoRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'content': !exists(json, 'content') ? undefined : json['content'],
        'isCompleted': !exists(json, 'is_completed') ? undefined : json['is_completed'],
    };
}

export function PatchedTodoRequestToJSON(value?: PatchedTodoRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'content': value.content,
        'is_completed': value.isCompleted,
    };
}

