/* tslint:disable */
/* eslint-disable */
/**
 * Todo List API
 * A basic todo list API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResendEmailVerification
 */
export interface ResendEmailVerification {
    /**
     * 
     * @type {string}
     * @memberof ResendEmailVerification
     */
    email?: string;
}

/**
 * Check if a given object implements the ResendEmailVerification interface.
 */
export function instanceOfResendEmailVerification(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ResendEmailVerificationFromJSON(json: any): ResendEmailVerification {
    return ResendEmailVerificationFromJSONTyped(json, false);
}

export function ResendEmailVerificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResendEmailVerification {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': !exists(json, 'email') ? undefined : json['email'],
    };
}

export function ResendEmailVerificationToJSON(value?: ResendEmailVerification | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
    };
}

