/* tslint:disable */
/* eslint-disable */
/**
 * Todo List API
 * A basic todo list API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TodoRequest
 */
export interface TodoRequest {
    /**
     * 
     * @type {string}
     * @memberof TodoRequest
     */
    content: string;
    /**
     * 
     * @type {boolean}
     * @memberof TodoRequest
     */
    isCompleted?: boolean;
}

/**
 * Check if a given object implements the TodoRequest interface.
 */
export function instanceOfTodoRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "content" in value;

    return isInstance;
}

export function TodoRequestFromJSON(json: any): TodoRequest {
    return TodoRequestFromJSONTyped(json, false);
}

export function TodoRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TodoRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'content': json['content'],
        'isCompleted': !exists(json, 'is_completed') ? undefined : json['is_completed'],
    };
}

export function TodoRequestToJSON(value?: TodoRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'content': value.content,
        'is_completed': value.isCompleted,
    };
}

