/* tslint:disable */
/* eslint-disable */
/**
 * Todo List API
 * A basic todo list API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * User model w/o password
 * @export
 * @interface UserDetailsRequest
 */
export interface UserDetailsRequest {
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     * @type {string}
     * @memberof UserDetailsRequest
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof UserDetailsRequest
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof UserDetailsRequest
     */
    lastName?: string;
}

/**
 * Check if a given object implements the UserDetailsRequest interface.
 */
export function instanceOfUserDetailsRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "username" in value;

    return isInstance;
}

export function UserDetailsRequestFromJSON(json: any): UserDetailsRequest {
    return UserDetailsRequestFromJSONTyped(json, false);
}

export function UserDetailsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserDetailsRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'username': json['username'],
        'firstName': !exists(json, 'first_name') ? undefined : json['first_name'],
        'lastName': !exists(json, 'last_name') ? undefined : json['last_name'],
    };
}

export function UserDetailsRequestToJSON(value?: UserDetailsRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
        'first_name': value.firstName,
        'last_name': value.lastName,
    };
}

